### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by pajso96** [asika32764/minify#1]
I get that when i try to minifiy CSS using addContent .

at vendor/asika/minify/src/CSS/CSSmin.php:787
  at Asika\Minifier\CSS\CSSmin->normalize_int('128M')
     (vendor/asika/minify/src/CSS/CSSmin.php:206)
  at Asika\Minifier\CSS\CSSmin->do_raise_php_limits()
     (vendor/asika/minify/src/CSS/CSSmin.php:71)

**Comment by pajso96** [comment]
I fixed that using intval(). 
`
if (is_string($size)) {

			switch (substr($size, -1)) {
				case 'M': case 'm': return intval($size) * 1048576;
				case 'K': case 'k': return intval($size) * 1024;
				case 'G': case 'g': return intval($size) * 1073741824;
			}
		}

`

**Comment by umutphp** [comment]
Hi @asika32764 ,

Can you please share the status of the issue? Did you have time to fix? Any plan to fix?

**Comment by asika32764** [comment]
Sorry, too busy to update project.

I'll merge your PR, thank you very mush.
